language: node_js
node_js:
  - 10.15.3
notifications:
  email: false
install:
  - npm install
jobs:
  include:
    - stage: "Lint, Test and Build"
    - script: npm run build && npm run lint
stages:
  - "Lint, Test and Build"
