language: node_js
node_js: node
notifications:
  email: false
install:
  - cd functions; npm install
jobs:
  include:
    - stage: "Lint, Test and Build"
    - script: npm run build && npm run lint
stages:
  - "Lint, Test and Build"