# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Lint and Build

on:
  pull_request:
    branches: [release, master]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Use Node.js
      uses: actions/setup-node@v1
    - name: install
      run: yarn install
    - name: lint
      run: yarn lint
    - name: build
      run: yarn build
      
